# Site settings
title: Lindsey Menges
email: lindseymenges@gmail.com
url: https://github.com/lindseymenges
description: "Personal website of programmer, nail artist, and author extraordinaire, Lindsey Menges"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/thedragonbabe
  - title: facebook
    url: http://facebook.com/nailsfornickels
  - title: github
    url: http://github.com/lindseymenges

# Postal address (add as many lines as necessary)
address:
  - line: San Jose, CA

# Credits content
credits: 'Jekyll theme: <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer</a>'

# Build settings
markdown: kramdown
permalink: pretty
